version: '3'

networks:
    nginx-php8-mysql8-mailcatcher:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php8-service
            - mysql8-service
        networks:
            - nginx-php8-mysql8-mailcatcher

    # php
    php8-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php8-container
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - nginx-php8-mysql8-mailcatcher

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        networks:
            - nginx-php8-mysql8-mailcatcher

    # mailcatcher
    mailcatcher-service:
        image: schickling/mailcatcher
        container_name: mailcatcher-container
        ports: [ "1025", "1080" ]
        networks:
            - nginx-php8-mysql8-mailcatcher
